---
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: gitsubmodule
  directory: /
  allow:
  - dependency-name: src/oci-build-task
  schedule:
    interval: weekly
